export const enDashboard = {
  // Dashboard Stats
  totalDebts: 'Total Debts',
  overdueDebts: 'Overdue Debts',
  paidThisMonth: 'Paid This Month',
  totalExpenses: 'Total Expenses (30d)',
  totalIncome: 'Total Income (30d)',
  netProfit: 'Net Profit',
  netLoss: 'Net Loss',

  // Dashboard Sections
  aiInsights: 'AI Insights',
  voiceCommand: 'Voice Command',
  predictiveAnalysis: 'Predictive Analysis',
  incomeBreakdown: 'Income Breakdown',
  expenseBreakdown: 'Expense Breakdown',
  cashFlowForecast: 'Cash Flow Forecast',

  // Dashboard Actions
  addDebt: 'Add Debt',
  addCustomer: 'Add Customer',
  addExpense: 'Add Expense',
  createReport: 'Create Report',
  exportData: 'Export Data',

  // Reports
  selectReport: 'Select a report to view',
  autoGenerated: 'Auto-generated',

  // Chart Labels
  revenueForecast: 'Revenue Forecast',
  expensesForecast: 'Expenses Forecast',
  netCashFlow: 'Net Cash Flow',

  // Customization
  customize: 'Customize',
  saveLayout: 'Save Layout',
  cancel: 'Cancel',
  
  // Financial Health
  financialHealthScore: 'Financial Health Score',
  financialHealthDetails: 'Financial Health Details',
  viewDetails: 'View Details',
  financialStatusGood: 'Good',
  financialStatusAverage: 'Average',
  financialStatusPoor: 'Poor',
  financialHealth: 'Financial Health',
};
