
export const ROUTES = {
  DASHBOARD: '/',
  SALES: '/sales',
  CUSTOMERS: '/customers',
  SUPPLIERS: '/suppliers',
  DEBTS: '/debts',
  EXPENSES: '/expenses',
  INCOME: '/income',
  INVENTORY: '/inventory',
  INVENTORY_IMPORT: '/inventory/import',
  NOTES: '/notes',
  REPORTS: '/reports',
  ACCOUNTING: '/accounting',
  TEAM: '/team',
  SETTINGS: '/settings',
  INTEGRATIONS: '/integrations',
  LOGIN: '/login',
  REGISTER: '/register',
  PURCHASES: '/purchases',
  PURCHASES_IMPORT: '/purchases/import',
  PROJECTS: '/projects',
  PROJECT_DETAILS: '/projects/:projectId',
  ACCEPT_INVITE: '/accept-invite/:token',
  VEHICLES: '/vehicles',
} as const;
