export const arDashboard = {
  // Dashboard Stats
  totalDebts: 'إجمالي الديون',
  overdueDebts: 'الديون المتأخرة',
  paidThisMonth: 'المدفوع هذا الشهر',
  totalExpenses: 'المصروفات (آخر 30 يوم)',
  totalIncome: 'الإيرادات (آخر 30 يوم)',
  netProfit: 'صافي الربح',
  netLoss: 'صافي الخسارة',

  // Dashboard Sections
  aiInsights: 'رؤى ذكية',
  voiceCommand: 'الأوامر الصوتية',
  predictiveAnalysis: 'التحليل التنبؤي',
  incomeBreakdown: 'تفاصيل الإيرادات',
  expenseBreakdown: 'تفاصيل المصروفات',
  cashFlowForecast: 'توقعات التدفق النقدي',
  
  // Dashboard Actions
  addDebt: 'إضافة دين جديد',
  addCustomer: 'إضافة عميل',
  addExpense: 'إضافة مصروف',
  createReport: 'إنشاء تقرير',
  exportData: 'تصدير البيانات',

  // Reports
  selectReport: 'اختر تقريرًا لعرضه',
  autoGenerated: 'تلقائي',

  // Chart Labels
  revenueForecast: 'توقعات الإيرادات',
  expensesForecast: 'توقعات المصروفات',
  netCashFlow: 'صافي التدفق النقدي',

  // Customization
  customize: 'تخصيص',
  saveLayout: 'حفظ التخطيط',
  cancel: 'إلغاء',
  
  // Financial Health
  financialHealthScore: 'مؤشر الصحة المالية',
  financialHealthDetails: 'تفاصيل الصحة المالية',
  viewDetails: 'عرض التفاصيل',
  financialStatusGood: 'جيد',
  financialStatusAverage: 'متوسط',
  financialStatusPoor: 'ضعيف',
  financialHealth: 'الصحة المالية',
};
